### ISSUE TITLE
Add posibility to use native es6 import

### ISSUE THREAD

**Issue by kakawajazz** [Grsmto/simplebar#146]
Is it possible to add such usage way as native imports?

When I use webpack this works great:
`import SimpleBar from './simplebar';`

But when I use native import with <script type="module"> I get
> Uncaught SyntaxError: The requested module does not provide an export named 'default'

**Comment by Grsmto** [comment]
Hi,

That's interesting. That's definitely something I would like to support yes.

**Comment by Grsmto** [comment]
Hey,
So I took a look at this but from what I understood of ES6 native modules, I can't have npm dependencies on my file and SimpleBar as several dependencies, so the script can't be loaded this way (or I'm missing something...).

```
import 'core-js/fn/array/from';
import scrollbarWidth from 'scrollbarwidth';
import debounce from 'lodash.debounce';
import ResizeObserver from 'resize-observer-polyfill';
```

These are referring to node_modules so the browser can't find them as from what I understood you need to reference a path. So maybe this could work if we were importing this way: `'./node_modules/scrollbarwidth` but then it wouldn't work for other environments...
So I'm not sure how to resolve this.

**Comment by lkraav** [comment]
Hi. I see `simplebar.esm.js` exists now, is this issue resolved?

**Comment by Grsmto** [comment]
We always had an esm version. What op wants is to be able to use SimpleBar with `<script type="module">` which doesn't work at the moment with the esm version I think.

**Comment by lkraav** [comment]
OK. I found this issue looking for a solution for our packaging problem

With `import SimpleBar from 'simplebar/dist/simplebar';` we get:

```
lerna ERR! yarn run dist stderr:
The 'this' keyword is equivalent to 'undefined' at the top level of an ES module, and has been rewritten
Error: 'default' is not exported by ../../node_modules/simplebar/dist/simplebar.js
    at error (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:9396:30)
    at Module.error (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13333:9)
    at handleMissingExport (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13255:21)
    at Module.traceVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13647:17)
    at ModuleScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:12354:39)
    at ChildScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)
    at FunctionScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)
    at ChildScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)
    at Identifier$1.bind (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:8315:40)
    at NewExpression.bind (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:7951:23)
error Command failed with exit code 1.
```

With `import SimpleBar from 'simplebar/dist/simplebar.esm.js';` we get:

```
lerna ERR! yarn run dist stderr:                                                                                                                                                                
Error: 'default' is not exported by ../../node_modules/lodash.throttle/index.js                                                                                                                 
    at error (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:9396:30)                                                                                      
    at Module.error (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13333:9)                                                                               
    at handleMissingExport (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13255:21)                                                                       
    at Module.traceVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:13647:17)                                                                      
    at ModuleScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:12354:39)                                                                  
    at FunctionScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)                                                                 
    at ChildScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)                                                                    
    at FunctionScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)                                                                 
    at ChildScope.findVariable (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:2963:38)
    at Identifier$1.bind (/home/leho/Documents/web-components/cxl-redesign/node_modules/rollup/dist/rollup.js:8315:40)
error Command failed with exit code 1.
```

Not entirely sure whether this is related to the original issue, or is something new?

**Comment by Grsmto** [comment]
@ikraav really weird issue, what environment are you in? Is that with Webpack?

**Comment by Manviel** [comment]
I also have similar issue. When using <script> i have an error Unexpected token '{'

**Comment by habibmousavi** [comment]
For the sake of a double check. I as well got an **Unexpected token '{'** when using Simplebar. When I reviewed the code, I came to notice that I had used **simplebar.min.css** in my **script** tag and not **simplebar.min.js**. Please double check that to make sure this simple typo is not your problem as well.

**Comment by Grsmto** [comment]
Closing this as it's pretty old. Please re-open a new issue related to the latest version if needed! Thanks.
