### ISSUE TITLE
Jest unit tests break with SimpleBar

### ISSUE THREAD

**Issue by adamk1230** [Grsmto/simplebar#447]
**Describe the bug**
Any component that is using SimpleBar will fail to render during unit tests.

**To Reproduce**
1. `npx create-react-app my-app`
2. `npm install simplebar-react --save`
3.  Add the following code to `App.js`
``` javascript
<SimpleBarReact style={{ height: '300px' }}>
      {[...Array(50)].map((x, i) => (
        <p key={i} className="odd">
          Some content
        </p>
      ))}
</SimpleBarReact>
```
4. `npm run test`
5. See error.

**Expected behavior**
Expect the test to not error out.
The observed error message:
```

    TypeError: e.MutationObserver is not a constructor

      4 |
      5 | test('renders learn react link', () => {
    > 6 |   const { getByText } = render(<App />);
        |                         ^
      7 |   const linkElement = getByText(/learn react/i);
      8 |   expect(linkElement).toBeInTheDocument();
      9 | });

      at t.e.initListeners (node_modules/simplebar-react/dist/simplebar-react.js:10:48742)
      at t.e.init (node_modules/simplebar-react/dist/simplebar-react.js:10:44607)
      at new t (node_modules/simplebar-react/dist/simplebar-react.js:10:43783)
      at node_modules/simplebar-react/dist/simplebar-react.js:10:57427
      at commitHookEffectList (node_modules/react-dom/cjs/react-dom.development.js:22030:26)
      at commitPassiveHookEffects (node_modules/react-dom/cjs/react-dom.development.js:22064:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at invokeEventListeners (H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at flushPassiveEffectsImpl (node_modules/react-dom/cjs/react-dom.development.js:25392:7)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority$2 (node_modules/react-dom/cjs/react-dom.development.js:12149:10)
      at flushPassiveEffects (node_modules/react-dom/cjs/react-dom.development.js:25361:12)
      at Object.<anonymous>.flushWork (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1041:10)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1155:9)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.<anonymous>.test (src/App.test.js:6:25)

  console.error H:/code/test/my-app2/node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: e.MutationObserver is not a constructor]
        at reportException (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at invokeEventListeners (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:385:16)
        at invokeGuardedCallback (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:440:31)
        at flushPassiveEffectsImpl (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:25392:7)
        at unstable_runWithPriority (C:\Developer\code\test\my-app2\node_modules\scheduler\cjs\scheduler.development.js:697:12) TypeError: e.MutationObserver is not a constructor
        at t.e.initListeners (C:\Developer\code\test\my-app2\node_modules\simplebar-react\dist\simplebar-react.js:10:48742)
        at t.e.init (C:\Developer\code\test\my-app2\node_modules\simplebar-react\dist\simplebar-react.js:10:44607)
        at new t (C:\Developer\code\test\my-app2\node_modules\simplebar-react\dist\simplebar-react.js:10:43783)
        at C:\Developer\code\test\my-app2\node_modules\simplebar-react\dist\simplebar-react.js:10:57427
        at commitHookEffectList (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:22030:26)
        at commitPassiveHookEffects (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:22064:11)
        at HTMLUnknownElement.callCallback (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:336:14)
        at invokeEventListeners (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (H:\code\test\my-app2\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:385:16)
        at invokeGuardedCallback (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:440:31)
        at flushPassiveEffectsImpl (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:25392:7)
        at unstable_runWithPriority (C:\Developer\code\test\my-app2\node_modules\scheduler\cjs\scheduler.development.js:697:12)
        at runWithPriority$2 (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:12149:10)
        at flushPassiveEffects (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom.development.js:25361:12)
        at Object.<anonymous>.flushWork (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom-test-utils.development.js:1041:10)
        at act (C:\Developer\code\test\my-app2\node_modules\react-dom\cjs\react-dom-test-utils.development.js:1155:9)
        at render (C:\Developer\code\test\my-app2\node_modules\@testing-library\react\dist\pure.js:82:26)
        at Object.<anonymous>.test (C:\Developer\code\test\my-app2\src\App.test.js:6:25)
        at Object.asyncJestTest (H:\code\test\my-app2\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
        at resolve (H:\code\test\my-app2\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (H:\code\test\my-app2\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
        at promise.then (H:\code\test\my-app2\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

  console.error node_modules/react-dom/cjs/react-dom.development.js:21843
    The above error occurred in the <SimpleBar> component:
        in SimpleBar (at App.js:25)
        in div (at App.js:24)
        in div (at App.js:9)
        in App (at App.test.js:6)

```

**Comment by iwd-silvac** [comment]
You have to mock mutation observer class, like
```javascript
global.MutationObserver = class {
      constructor() {}
      disconnect() {}
      observe() {}
    };
```

**Comment by charlesCassioSilva** [comment]
You have to mock the mutation observer class like:

```javascript
global.MutationObserver = class {
      constructor() {}
      disconnect() {}
      observe() {}
    };
```
