### ISSUE TITLE
Lodash Error in beta.7

### ISSUE THREAD

**Issue by mehdiraized** [Grsmto/simplebar#531]
**Describe the bug**
```
/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/apple/Desktop/Project/node_modules/simplebar/dist/simplebar.umd.js:14:149
    at Object.<anonymous> (/Users/apple/Desktop/Project/node_modules/simplebar/dist/simplebar.umd.js:22:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Your environment**

| Software         | Version(s) |
| ---------------- | ---------- |
| SimpleBar        | 6.0.0-beta.7
| Browser          | Chrome
| Operating System | Macos 11

**Comment by Grsmto** [comment]
Hopefully should be fixed now!
