### ISSUE TITLE
Version 6.1.0 does not working with jQuery

### ISSUE THREAD

**Issue by matsu-motsu** [Grsmto/simplebar#639]
An error occurs in the console when initializing the element.
`new SimpleBar($('#myElement')[0]);`

~~~
"jQuery.Deferred exception: SimpleBar is not a constructor" "TypeError: SimpleBar is not a constructor
    at HTMLDocument.<anonymous> (https://cdpn.io/cpe/boomboom/pen.js?key=pen.js-52e744d1-db04-f4ad-d728-e4e3dd5d7b27:2:3)
    at e (https://code.jquery.com/jquery-3.6.3.min.js:2:30310)
    at t (https://code.jquery.com/jquery-3.6.3.min.js:2:30612)" undefined
~~~

**Example**
- Working as expected
  https://codepen.io/matsu-motsu/pen/xxJXyRo
- Not working as expected, an error is displayed in the console
  https://codepen.io/matsu-motsu/pen/NWBaOgX

*Version*
- SimpleBar@6.1.0
- jQuery@3.6.3

Thank you.

**Comment by Grsmto** [comment]
Thanks for the report, it should work on the latest version!

**Comment by matsu-motsu** [comment]
@Grsmto 
Fixed, thank you!
